In [46]:
import tensorflow as tf
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [48]:
data = pd.read_csv("Iris.csv")
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [50]:
x = data.drop("Species", axis = 1)
x

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [52]:
data.Species

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [54]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Species'] = le.fit_transform(data['Species'])
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [56]:
y = data['Species']
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int32

In [58]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [60]:
x_train.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
5      6            5.4           3.9            1.7           0.4
112  113            6.8           3.0            5.5           2.1
36    37            5.5           3.5            1.3           0.2
108  109            6.7           2.5            5.8           1.8
119  120            6.0           2.2            5.0           1.5

In [62]:
y_train

5      0
112    2
36     0
108    2
119    2
      ..
11     0
54     1
76     1
100    2
37     0
Name: Species, Length: 120, dtype: int32

In [72]:
y_train = tf.keras.utils.to_categorical(y_train, num_classes = 3)
print(y_train[:3])

[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [74]:
from keras.models import Sequential
from keras.layers import Dense

In [76]:
model = Sequential()
model.add(Dense(units = 8, activation = "relu",input_shape= (x_train.shape[-1], )))
model.add(Dense(units = 8, activation = "relu"))

model.add(Dense(units = 3, activation = "softmax"))

C:\Users\91883\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [78]:
model.compile(optimizer = 'Adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                      │ (None, 8)                   │              48 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (None, 8)                   │              72 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ (None, 3)                   │              27 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 147 (588.00 B)

 Trainable params: 147 (588.00 B)

 Non-trainable params: 0 (0.00 B)

In [82]:
model.fit(x_train, y_train, epochs =20, validation_split = 0.1 )

Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 162ms/step - accuracy: 0.3218 - loss: 3.5883 - val_accuracy: 0.4167 - val_loss: 1.5824
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.4616 - loss: 1.3964 - val_accuracy: 0.4167 - val_loss: 1.3780
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5669 - loss: 1.2094 - val_accuracy: 0.4167 - val_loss: 1.4851
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.4959 - loss: 1.3352 - val_accuracy: 0.4167 - val_loss: 1.3297
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.5007 - loss: 1.1447 - val_accuracy: 0.4167 - val_loss: 1.0639
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.5859 - loss: 0.8049 - val_accuracy: 0.4167 - val_loss: 0.8689
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5866 - loss: 0.7641 - val_accuracy: 0.5000 - val_loss: 0.8232
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.4648 - loss: 0.7738 - val_accuracy: 0.5000 - val_loss: 0.7825

In [87]:
prediction = model.predict(x_test)
print(prediction[:5])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step
[[0.04249552 0.4602823  0.49722221]
 [0.00828336 0.17144804 0.8202686 ]
 [0.77803    0.12339772 0.09857226]
 [0.14404367 0.62028646 0.23566985]
 [0.7742331  0.12576635 0.10000056]]


In [91]:
prediction = np.argmax(prediction, axis=-1)
print(prediction[:5]) 

[2 2 0 1 0]


In [93]:
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, prediction))

0.8666666666666667
